services:
  bot:
    build: .
    container_name: smart_procure_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Чтобы база данных сохранялась при перезапуске
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: smart_procure_mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: